insert into Wrote values(4, 'Jurassic Park');
insert into Wrote values(7, 'The Goal');
insert into Wrote values(1, 'Heidi');
insert into Wrote values(8, 'Rework');
insert into Wrote values(5, 'Rework');
insert into Wrote values(1, 'Anna Karenina');
insert into Wrote values(2, 'Rework');
insert into Wrote values(3, 'The Lion King');
insert into Wrote values(4, 'Rich Dad');
insert into Wrote values(8, 'The Power of Habit');